driver_plugin: vagrant

provisioner:
  name: chef_zero

# Must run vagrant plugin install vagrant-winrm 
# in order for the winrm transport to work
platforms:
- name: windows-2012R2
  driver_config:
    box: mwrock/Windows2012R2
    communicator: winrm
    vm_hostname: false
  transport:
    name: winrm

- name: ubuntu-12.04
  run_list:
  - recipe[ubuntu]
  driver_config:
    box: hashicorp/precise64

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[minecraft]
  attributes:
    minecraft:
      accept_eula: true
