---
#driver_plugin: digitalocean
#driver_config:
#  flavor_id: 63
#  require_chef_omnibus: latest

driver:
  name: vagrant
  customize:
    memory: 2048
provisioner:
  name: chef_solo
  client_rb:
    audit_mode: :enabled
  require_chef_omnibus: 12.4.1


platforms:
- name: ubuntu-16.04
  run_list:
  - recipe[ubuntu]
  attributes:
    minecraft:
      accept_eula: true
- name: ubuntu-14.10
  run_list:
  - recipe[ubuntu]
  attributes:
    minecraft:
      accept_eula: true
- name: ubuntu-15.04
  run_list:
  - recipe[ubuntu]
  attributes:
    minecraft:
      accept_eula: true
- name: debian-7.0
  provisioner:
    sudo: false
  busser:
    sudo: false
  run_list:
  - recipe[apt]
  attributes:
    minecraft:
      accept_eula: true
- name: debian-6.0
  run_list:
  - recipe[apt]
  attributes:
    minecraft:
      accept_eula: true
- name: centos-6.5
  run_list:
  - recipe[yum-epel]
  attributes:
    minecraft:
      accept_eula: true
- name: centos-7.0
  run_list:
  - recipe[yum-epel]
  attributes:
    minecraft:
      accept_eula: true
suites:
- name: default
  run_list:
  - recipe[minecraft]
  attributes:
- name: spigot
  run_list:
  - recipe[git]
  - recipe[minecraft]
  - recipe[minecraft-test]
  attributes:
    minecraft:
      install_type: "spigot"
      accept_eula: true
    java:
      jdk_version: "7"
      accept_license_agreement: true
- name: bukkit
  run_list:
  - recipe[git]
  - recipe[minecraft]
  - recipe[minecraft-test]
  attributes:
    minecraft:
      install_type: "bukkit"
      accept_eula: true
    java:
      jdk_version: "7"
      accept_license_agreement: true

